liquibase-database:
  user: user
  schema: public
  url: jdbc:postgresql://localhost/rocket-fuel

database:
  user: user
  schema: public
  url: jdbc:postgresql://localhost/rocket-fuel

applicationTokenConfig:
  secret: a-valid-but-not-secure-secret

openId:
  issuer: https://accounts.google.com
  jwksUri: https://www.googleapis.com/oauth2/v3/certs
  clientId: client-id-found-in-google-console-for-example