# Set up postgres with:
# docker run --name some-postgres -p 15432:5432 -e POSTGRES_PASSWORD=mysecretpassword -e POSTGRES_DB=rocket-fuel -d postgres

liquibase-database:
  user: postgres
  password: mysecretpassword
  schema: public
  url: jdbc:postgresql://localhost:15432/rocket-fuel

database:
  user: postgres
  password: mysecretpassword
  schema: public
  url: jdbc:postgresql://localhost:15432/rocket-fuel