liquibase-database:
  user: dbuser
  schema: <db-schema>
  password: super-secret-password
  url: jdbc:postgresql://localhost/databasename

database:
  user: dbuser
  password: super-secret-password
  schema: <db-schema>
  url: jdbc:postgresql://localhost/databasename

applicationTokenConfig:
  secret: a-valid-but-not-secure-secret

slack:
  botUserToken: <your-slack-app-bot-user-token>
  apiToken: <your-slack-app-api-token>

openId:
  issuer: https://accounts.google.com
  jwksUri: https://www.googleapis.com/oauth2/v3/certs
  clientId: <client-id-found-in-google-console-for-example>

logging:
  # Log requests to file, other level INFO to redis (kibana)
  additivity:
    com.fortnox.reactivewizard.ReactiveWizardServer: false
    se.fortnox.reactivewizard.jaxrs.JaxRsResource: false
  levels:
    com.fortnox.reactivewizard.ReactiveWizardServer: INFO, file
    se.fortnox.reactivewizard.jaxrs.JaxRsResource: INFO, file
  appenders:
    file:
      file: /tmp/slackoverflow.log

    stdout:
      layout: net.logstash.log4j.JSONEventLayoutV1
      threshold: INFO
