liquibase-database:
  user: utvjava
  schema: rocket-fuel-tf
  url: jdbc:postgresql://192.168.3.41/javaservices_utv
  password: fortnox1

database:
  user: utvjava
  schema: rocket-fuel-tf
  url: jdbc:postgresql://192.168.3.41/javaservices_utv
  password: fortnox1

applicationTokenConfig:
  secret: 8hDBY692NW3wEssD9GgzeJtsk8JqXQZJYYTPCqhBtA22v7RS6meADqMjPFAt6AY2

openId:
  issuer: accounts.google.com
  jwksUri: https://www.googleapis.com/oauth2/v3/certs
  clientId: 921310387394-ci437tfrcc4r1o30hqs3mrnmrpp40oj0.apps.googleusercontent.com
