liquibase-database:
  user: postgres
  schema: public
  password: mysecretpassword
  url: jdbc:postgresql://localhost:15432/rocket-fuel

database:
  user: postgres
  schema: public
  password: mysecretpassword
  url: jdbc:postgresql://localhost:15432/rocket-fuel

applicationTokenConfig:
  secret: a-valid-but-not-secure-secret
  domain: <your-domain-where-the-application-is-hosted>

slack:
  botUserToken: <your-slack-app-bot-user-token>
  apiToken: <your-slack-app-api-token>

openId:
  issuer: accounts.google.com
  jwksUri: https://www.googleapis.com/oauth2/v3/certs
  clientId: 921310387394-ci437tfrcc4r1o30hqs3mrnmrpp40oj0.apps.googleusercontent.com

logging:
  additivity:
    com.fortnox.reactivewizard.ReactiveWizardServer: false
    se.fortnox.reactivewizard.jaxrs.JaxRsResource: false
  levels:
    com.fortnox.reactivewizard.ReactiveWizardServer: INFO
    se.fortnox.reactivewizard.jaxrs.JaxRsResource: INFO
  appenders:
    stdout:
      threshold: INFO
