liquibase-database:
  user: utvjava
  schema: rocket-fuel-tf
  url: jdbc:postgresql://192.168.3.41/javaservices_utv
  password: fortnox1

database:
  user: utvjava
  schema: rocket-fuel-tf
  url: jdbc:postgresql://192.168.3.41/javaservices_utv
  password: fortnox1

applicationTokenConfig:
  secret: 8hDBY692NW3wEssD9GgzeJtsk8JqXQZJYYTPCqhBtA22v7RS6meADqMjPFAt6AY2
