language: java

jdk:
  - openjdk11

branches:
  only:
    - master

after_success:
  - bash <(curl -s https://codecov.io/bash)

services:
  - docker

script:
  - sonar-scanner

addons:
  sonarcloud:
    organization: "fortnoxab"
