language: java

jdk:
  - openjdk11

branches:
  only:
    - master

after_success:
  - bash <(curl -s https://codecov.io/bash)

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
services:
  - docker

addons:
  sonarcloud:
    organization: "fortnoxab"
